2023-07-28 04:54:28,099 INFO: Highlyfe startup [in /Users/danielweir/highlyfe3/app/__init__.py:75]
2023-07-28 04:55:09,649 INFO: Highlyfe startup [in /Users/danielweir/highlyfe3/app/__init__.py:75]
2023-07-28 04:58:27,351 INFO: Highlyfe startup [in /Users/danielweir/highlyfe3/app/__init__.py:75]
2023-07-28 05:01:10,109 INFO: Highlyfe startup [in /Users/danielweir/highlyfe3/app/__init__.py:75]
2023-07-28 13:19:27,280 ERROR: Exception on /user/Bron/popup [GET] [in /Users/danielweir/highlyfe3/venv/lib/python3.9/site-packages/flask/app.py:1414]
Traceback (most recent call last):
  File "/Users/danielweir/highlyfe3/venv/lib/python3.9/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/danielweir/highlyfe3/venv/lib/python3.9/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/danielweir/highlyfe3/venv/lib/python3.9/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/danielweir/highlyfe3/venv/lib/python3.9/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/Users/danielweir/highlyfe3/venv/lib/python3.9/site-packages/flask_login/utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "/Users/danielweir/highlyfe3/app/main/routes.py", line 306, in user_popup
    return render_template('user_popup.html', user=user, form=form)
  File "/Users/danielweir/highlyfe3/venv/lib/python3.9/site-packages/flask/templating.py", line 150, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
  File "/Users/danielweir/highlyfe3/venv/lib/python3.9/site-packages/jinja2/environment.py", line 1081, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/Users/danielweir/highlyfe3/venv/lib/python3.9/site-packages/jinja2/environment.py", line 1010, in get_template
    return self._load_template(name, globals)
  File "/Users/danielweir/highlyfe3/venv/lib/python3.9/site-packages/jinja2/environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/Users/danielweir/highlyfe3/venv/lib/python3.9/site-packages/jinja2/loaders.py", line 138, in load
    code = environment.compile(source, name, filename)
  File "/Users/danielweir/highlyfe3/venv/lib/python3.9/site-packages/jinja2/environment.py", line 768, in compile
    self.handle_exception(source=source_hint)
  File "/Users/danielweir/highlyfe3/venv/lib/python3.9/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/Users/danielweir/highlyfe3/app/templates/user_popup.html", line 14, in template
    {{ ('%(count)d followers', count=user.followers.count()) }},
jinja2.exceptions.TemplateSyntaxError: expected token ')', got '='
2023-07-28 13:19:31,552 ERROR: Exception on /user/Bron/popup [GET] [in /Users/danielweir/highlyfe3/venv/lib/python3.9/site-packages/flask/app.py:1414]
Traceback (most recent call last):
  File "/Users/danielweir/highlyfe3/venv/lib/python3.9/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/danielweir/highlyfe3/venv/lib/python3.9/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/danielweir/highlyfe3/venv/lib/python3.9/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/danielweir/highlyfe3/venv/lib/python3.9/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/Users/danielweir/highlyfe3/venv/lib/python3.9/site-packages/flask_login/utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "/Users/danielweir/highlyfe3/app/main/routes.py", line 306, in user_popup
    return render_template('user_popup.html', user=user, form=form)
  File "/Users/danielweir/highlyfe3/venv/lib/python3.9/site-packages/flask/templating.py", line 150, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
  File "/Users/danielweir/highlyfe3/venv/lib/python3.9/site-packages/jinja2/environment.py", line 1081, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/Users/danielweir/highlyfe3/venv/lib/python3.9/site-packages/jinja2/environment.py", line 1010, in get_template
    return self._load_template(name, globals)
  File "/Users/danielweir/highlyfe3/venv/lib/python3.9/site-packages/jinja2/environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/Users/danielweir/highlyfe3/venv/lib/python3.9/site-packages/jinja2/loaders.py", line 138, in load
    code = environment.compile(source, name, filename)
  File "/Users/danielweir/highlyfe3/venv/lib/python3.9/site-packages/jinja2/environment.py", line 768, in compile
    self.handle_exception(source=source_hint)
  File "/Users/danielweir/highlyfe3/venv/lib/python3.9/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/Users/danielweir/highlyfe3/app/templates/user_popup.html", line 14, in template
    {{ ('%(count)d followers', count=user.followers.count()) }},
jinja2.exceptions.TemplateSyntaxError: expected token ')', got '='
2023-07-28 13:22:03,414 INFO: Highlyfe startup [in /Users/danielweir/highlyfe3/app/__init__.py:75]
2023-07-28 13:24:23,955 INFO: Highlyfe startup [in /Users/danielweir/highlyfe3/app/__init__.py:75]
2023-07-28 13:24:50,036 ERROR: Exception on /user/Bron/popup [GET] [in /Users/danielweir/highlyfe3/venv/lib/python3.9/site-packages/flask/app.py:1414]
Traceback (most recent call last):
  File "/Users/danielweir/highlyfe3/venv/lib/python3.9/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/danielweir/highlyfe3/venv/lib/python3.9/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/danielweir/highlyfe3/venv/lib/python3.9/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/danielweir/highlyfe3/venv/lib/python3.9/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/Users/danielweir/highlyfe3/venv/lib/python3.9/site-packages/flask_login/utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "/Users/danielweir/highlyfe3/app/main/routes.py", line 306, in user_popup
    return render_template('user_popup.html', user=user, form=form)
  File "/Users/danielweir/highlyfe3/venv/lib/python3.9/site-packages/flask/templating.py", line 150, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
  File "/Users/danielweir/highlyfe3/venv/lib/python3.9/site-packages/jinja2/environment.py", line 1081, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/Users/danielweir/highlyfe3/venv/lib/python3.9/site-packages/jinja2/environment.py", line 1010, in get_template
    return self._load_template(name, globals)
  File "/Users/danielweir/highlyfe3/venv/lib/python3.9/site-packages/jinja2/environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/Users/danielweir/highlyfe3/venv/lib/python3.9/site-packages/jinja2/loaders.py", line 138, in load
    code = environment.compile(source, name, filename)
  File "/Users/danielweir/highlyfe3/venv/lib/python3.9/site-packages/jinja2/environment.py", line 768, in compile
    self.handle_exception(source=source_hint)
  File "/Users/danielweir/highlyfe3/venv/lib/python3.9/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/Users/danielweir/highlyfe3/app/templates/user_popup.html", line 76, in template
    {% else %}
jinja2.exceptions.TemplateSyntaxError: Encountered unknown tag 'else'.
2023-07-28 13:26:55,696 INFO: Highlyfe startup [in /Users/danielweir/highlyfe3/app/__init__.py:75]
2023-07-28 13:29:23,715 INFO: Highlyfe startup [in /Users/danielweir/highlyfe3/app/__init__.py:75]
2023-07-28 13:31:00,141 INFO: Highlyfe startup [in /Users/danielweir/highlyfe3/app/__init__.py:75]
2023-07-28 13:32:14,490 INFO: Highlyfe startup [in /Users/danielweir/highlyfe3/app/__init__.py:75]
2023-07-28 13:32:33,837 INFO: Highlyfe startup [in /Users/danielweir/highlyfe3/app/__init__.py:75]
2023-07-28 13:33:29,776 INFO: Highlyfe startup [in /Users/danielweir/highlyfe3/app/__init__.py:75]
2023-07-28 13:34:01,645 INFO: Highlyfe startup [in /Users/danielweir/highlyfe3/app/__init__.py:75]
2023-07-28 13:34:50,293 INFO: Highlyfe startup [in /Users/danielweir/highlyfe3/app/__init__.py:75]
2023-07-28 13:35:40,452 INFO: Highlyfe startup [in /Users/danielweir/highlyfe3/app/__init__.py:75]
2023-07-28 13:36:21,941 INFO: Highlyfe startup [in /Users/danielweir/highlyfe3/app/__init__.py:75]
2023-07-28 13:39:27,583 INFO: Highlyfe startup [in /Users/danielweir/highlyfe3/app/__init__.py:75]
2023-07-28 13:40:45,515 INFO: Highlyfe startup [in /Users/danielweir/highlyfe3/app/__init__.py:75]
2023-07-28 13:41:32,409 INFO: Highlyfe startup [in /Users/danielweir/highlyfe3/app/__init__.py:75]
2023-07-28 13:44:19,031 INFO: Highlyfe startup [in /Users/danielweir/highlyfe3/app/__init__.py:75]
2023-07-28 13:48:04,992 INFO: Highlyfe startup [in /Users/danielweir/highlyfe3/app/__init__.py:75]
2023-07-28 16:14:05,312 INFO: Highlyfe startup [in /Users/danielweir/highlyfe3/app/__init__.py:75]
2023-07-28 16:14:14,545 INFO: Highlyfe startup [in /Users/danielweir/highlyfe3/app/__init__.py:75]
2023-07-28 16:14:20,233 INFO: Highlyfe startup [in /Users/danielweir/highlyfe3/app/__init__.py:75]
